[build]
  base    = "site"
  publish = "public"
  command = "make"
  
  [context.production]
  command = "make production"
  [context.production.environment]
    ACCESS_TOKEN = "super secret"
    
[context.deploy-preview.environment]
  ACCESS_TOKEN = "not so secret"
  
  [context.branch-deploy]
  command = "make staging"

[context.feature]
  command = "make feature"

[context."features/branch"]
  command = "gulp"
