<%@ Page Title="" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="Services.aspx.cs" Inherits="TrendMotors2.WebForm8" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <h1 class="m_5224003110273553242red" style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; box-sizing: border-box; font-weight: 400; line-height: 1.1; margin-top: 0px; margin-bottom: 10px;"><h1 class="text-center" style="color: #000080; font-family: 'Comic Sans MS'"> &lt;.. Services ..></h1>
     <div class="info" style="border-style: none; border-color: #FFFFFF; margin-left: 40px;">
    <h2 style="font-size: x-large; font-family: 'Lucida Bright'; color: #FF0000; font-weight: bold; text-decoration: underline blink; text-transform: capitalize" class="text-center"> CAR FINANCE:</h2>
    <h2 class="m_5224003110273553242red" style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; box-sizing: border-box; font-weight: 400; line-height: 1.1; margin-top: 0px; margin-bottom: 10px;"><font size="3" style="margin-left: 40px"><span style="background-color: rgba(255, 255, 255, 0); font-weight: bold; font-family: Calibri; font-size:large">Looking for fast, competitive car finance?</span></font></h2>
   

    
    <p style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; box-sizing: border-box; margin: 0px 0px 20px 40px; line-height: 1.8;">
        <span style="background-color: rgba(255, 255, 255, 0);">We can help. Setting you up with the right vehicle finance for your needs, is what we do.</span></p>
    <h2 class="m_5224003110273553242red" style="color: rgb(34, 34, 34); font-family: Calibri; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; box-sizing: border-box; line-height: 1.1; margin-top: 0px; margin-bottom: 10px; font-size: medium;"><span style="font-weight: bold; font-size: large; font-family:Calibri">Get in Touch today...</span></h2>
    <ul style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; box-sizing: border-box; margin: 0px 0px 30px; list-style: none; padding-left: 0px;">
        <li style="margin-left: 15px; text-indent: 0px; box-sizing: border-box; line-height: 1.42857; padding-left: 1.2em; margin-bottom: 12px;"><span style="background-color: rgba(255, 255, 255, 0);">Are shopping for a new car and want to know how much you can spend</span></li>
        <li style="margin-left: 15px; text-indent: 0px; box-sizing: border-box; line-height: 1.42857; padding-left: 1.2em; margin-bottom: 12px;"><span style="background-color: rgba(255, 255, 255, 0);">Owe money on your existing car, but want a better deal on your vehicle finance</span></li>
        <li style="margin-left: 15px; text-indent: 0px; box-sizing: border-box; line-height: 1.42857; padding-left: 1.2em; margin-bottom: 12px;"><span style="background-color: rgba(255, 255, 255, 0);">Are looking for No Deposit car finance</span></li>
        <li style="margin-left: 15px; text-indent: 0px; box-sizing: border-box; line-height: 1.42857; padding-left: 1.2em; margin-bottom: 12px;"><span style="background-color: rgba(255, 255, 255, 0);">Would like to use your existing car as a trade-in</span></li>
        <li style="margin-left: 15px; text-indent: 0px; box-sizing: border-box; line-height: 1.42857; padding-left: 1.2em; margin-bottom: 12px;"><span style="background-color: rgba(255, 255, 255, 0);">Have had a credit issue and would like to know what your options are</span></li>
        <li style="margin-left: 15px; text-indent: 0px; box-sizing: border-box; line-height: 1.42857; padding-left: 1.2em; margin-bottom: 12px;"><span style="background-color: rgba(255, 255, 255, 0);">Want straight-forward, pre-approved vehicle finance, fast.</span></li>
    </ul>
    <p style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; box-sizing: border-box; margin: 0px 0px 20px; line-height: 1.8;">
        <span style="background-color: rgba(255, 255, 255, 0);">Whether you are self-employed, working, or a stay-at-home parent, we can help with competitive vehicle finance fast. In most cases, our car loans are more competitive than the banks.&nbsp;</span><span style="background-color: rgba(255, 255, 255, 0); font-size: medium;">Fast, flexible car finance:</span></p>
    <ul style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; box-sizing: border-box; margin: 0px 0px 30px; list-style: none; padding-left: 0px;">
        <li style="margin-left: 15px; text-indent: 0px; box-sizing: border-box; line-height: 1.42857; padding-left: 1.2em; margin-bottom: 12px;"><span style="background-color: rgba(255, 255, 255, 0);">No Deposit vehicle finance options</span></li>
        <li style="margin-left: 15px; text-indent: 0px; box-sizing: border-box; line-height: 1.42857; padding-left: 1.2em; margin-bottom: 12px;"><span style="background-color: rgba(255, 255, 255, 0);">Terms from 6 months to 5 years</span></li>
        <li style="margin-left: 15px; text-indent: 0px; box-sizing: border-box; line-height: 1.42857; padding-left: 1.2em; margin-bottom: 12px;"><span style="background-color: rgba(255, 255, 255, 0);">Competitive interest rates</span></li>
        <li style="margin-left: 15px; text-indent: 0px; box-sizing: border-box; line-height: 1.42857; padding-left: 1.2em; margin-bottom: 12px;"><span style="background-color: rgba(255, 255, 255, 0);">Easy weekly, fortnightly or monthly payments</span></li>
    </ul>
    <p style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; box-sizing: border-box; margin: 0px 0px 20px; line-height: 1.8;">
        <span style="background-color: rgba(255, 255, 255, 0);">Real people make our lending decisions – not computers. We get to know our customers, what they need and how their vehicle finance should best work for them. We’re proud of our role in the community, which is all about treating our customers the way we’d like to be treated. How can we help you?</span></p>
    <br class="Apple-interchange-newline" />
        </div>
        <br />
        <br />
         <h2 style="font-size: x-large; font-family: 'Lucida Bright'; color: #FF0000; font-weight: bold; text-decoration: underline blink; text-transform: capitalize" class="text-center"> MECHANICAL WARRANTY:</h2>
    <span style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; background-color: rgba(255, 255, 255, 0);"><strong style="box-sizing: inherit; line-height: inherit; text-align: center; outline: none !important;">
    <div style="text-align: start;" class="text-left">
        <strong style="box-sizing: inherit; line-height: inherit; outline: none !important;font-family:Calibri; font-size:large; font-weight:bold">NEW ZEALAND'S LEADING Mechanical Cover</strong></div>
    </strong></span>
    <div style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
        <span style="background-color: rgba(255, 255, 255, 0);">
        <br />
        Purchasing a Mechanical warranty from Trend Motors has just got that much better. Not only will you drive away knowing you are covered by New Zealand&#39;s leading warranty cover but you would be paying less than normal most competitive price, Saving you $$$ Money.<br />
        </span>
    </div>
    <span style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: large; font-weight:bold; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; background-color: rgba(255, 255, 255, 0);"><strong style="box-sizing: inherit; line-height: inherit; outline: none !important;">
    
        BEST PRICE! BEST QUALITY! BEST WARRANTIES!
   
    </strong></span>

    <div style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
        <span style="background-color: rgba(255, 255, 255, 0);">
        <br />
       For a limited time you can qualify for a Service and WOF plan to Match?? YES!!You could qualify to get your next 1, 2, or 3 years Servicing and WOF inspection for FREETerms and conditions apply.
     </span>
    </div>
        <br />
        <br />
  
</asp:Content>
